// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA3SgvSnGYxXq5FSGbJBayqgyWcz9rRF0',
    appId: '1:134740923705:web:1235d464fe9715c1b584e8',
    messagingSenderId: '134740923705',
    projectId: 'allevents-task-f83c4',
    authDomain: 'allevents-task-f83c4.firebaseapp.com',
    storageBucket: 'allevents-task-f83c4.firebasestorage.app',
    measurementId: 'G-L3CDCWTY8L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr8k5GqaJbV_L7yfvPtywi984DeFkNEMg',
    appId: '1:134740923705:android:a5563e009a18c0e9b584e8',
    messagingSenderId: '134740923705',
    projectId: 'allevents-task-f83c4',
    storageBucket: 'allevents-task-f83c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA_RzcgvBLadPZ5x5RE_TSVg99C0I8jjI',
    appId: '1:134740923705:ios:4aa9befdc1145355b584e8',
    messagingSenderId: '134740923705',
    projectId: 'allevents-task-f83c4',
    storageBucket: 'allevents-task-f83c4.firebasestorage.app',
    iosBundleId: 'com.example.alleventsTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDA_RzcgvBLadPZ5x5RE_TSVg99C0I8jjI',
    appId: '1:134740923705:ios:4aa9befdc1145355b584e8',
    messagingSenderId: '134740923705',
    projectId: 'allevents-task-f83c4',
    storageBucket: 'allevents-task-f83c4.firebasestorage.app',
    iosBundleId: 'com.example.alleventsTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAA3SgvSnGYxXq5FSGbJBayqgyWcz9rRF0',
    appId: '1:134740923705:web:5f39101fdde6267fb584e8',
    messagingSenderId: '134740923705',
    projectId: 'allevents-task-f83c4',
    authDomain: 'allevents-task-f83c4.firebaseapp.com',
    storageBucket: 'allevents-task-f83c4.firebasestorage.app',
    measurementId: 'G-NYR44RBWXJ',
  );
}
